version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.1.0
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run: echo "This is the build job"
  test:
    docker:
      - image: cimg/node:16.1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: npm install
      - run:
          name: Run tests with JUnit as reporter
          command: npm test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage
      - run: 
          name: Curl AWS CLI
          command: curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run:
          name: Send to codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -Z   
      - run: 
          name: Unzip AWS CLI
          command: unzip -q -o awscliv2.zip
      - run:
          name: Install AWS CLI
          command: sudo ./aws/install
      - run:
          name: Remove AWS CLI Installer
          command: rm awscliv2.zip
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - deploy:
          command: |
              sudo mv -- test-results $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD
              aws s3 cp $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD s3://test-results-bohrman --metadata '{\"git_sha1\":\"$CIRCLE_SHA1\"}'
workflows:
  build_and_test:
    jobs:
      - build
      - test